[project]
name = "uncertain_lang"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.3",
    "pytest>=8.3.4",
    "hypothesis>=6.126.0",
]

[project.scripts]
uncertain = "uncertain_lang.cli:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
