"""Regenerate docs/error-catalog.md from the diagnostic KINDS table and real compiler output.

    uv run python scripts/gen_error_catalog.py
"""
import os
import sys
import tempfile

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))

from uncertain.parser import parse, ParseError
from uncertain.lexer import LexerError
from uncertain.ast_nodes import Span
from uncertain.typechecker import TypeContext, check_program
from uncertain.diagnostics import KINDS, Diagnostic, format_diagnostic

# One small program per diagnostic kind, showing a typical way to trigger it.
EXAMPLES = {
    "syntax-error": "let a = sensor_read(;",
    "type-mismatch": "let reading: Measured<Normal(10.0, 2.0)> = sensor_read();",
    "undefined-var": "let y = x + 1.0;",
    "immutable-assign": "let total = 0;\ntotal = total + sensor_read();",
    "math-domain-error": "let a = sensor_read() - 15.0;\nlet b = sqrt(a);",
    "approximation-warning": "let u = uniform_read();\nlet n = sensor_read();\nlet c = u * n;",
    "delta-method-warning": "let a = normal_read(1.0, 2.0);\nlet b = 10.0 / a;",
    "uncertain-branch": "let a = sensor_read();\nvar b = 0;\nif (a > 5.0) {\n    b = 1;\n}",
    "loop-limit": "var i = 0;\nwhile (i >= 0) {\n    i = i + 1;\n}",
    "recursion-limit": "fn f(x) {\n    return f(x);\n}\nlet y = f(1);",
    "invalid-operand": "let readings = [sensor_read(), sensor_read()];\nlet total = readings + 1;",
    "not-constant": "let lam = sensor_read();\nlet p = poisson_read(lam);",
    "unknown-function": "let b = sqr(4.0);",
    "arity-mismatch": "let b = sqrt(4.0, 2.0);",
    "invalid-return": "fn f(x) {\n    let y = x * 2;\n}\nlet z = f(1);",
    "import-error": "import constants as c;\nlet g = c.g;",
    "internal-error": None,
}

def render(kind: str, source: str) -> str:
    lines = source.splitlines()
    with tempfile.TemporaryDirectory() as tmp:
        try:
            stmts, expr = parse(source)
        except (ParseError, LexerError) as e:
            diags = [Diagnostic("syntax-error", Span(e.line, e.col, 1), extra={"msg": str(e)})]
        else:
            diags = check_program(stmts, TypeContext(base_dir=tmp), expr)
    matching = [d for d in diags if d.kind == kind]
    assert matching, f"example for {kind} produced {[d.kind for d in diags]}"
    text = format_diagnostic(matching[0], lines)
    return text.replace(tmp + os.sep, "<dir>/")

def main():
    out = [
        "# Uncertain Error Catalog",
        "",
        "This catalog documents the structured diagnostics emitted by the `uncertain` compiler and type checker.",
        "Every diagnostic pinpoints the location of the issue. Run `uncertain --explain <code>` for the same",
        "explanations on the command line.",
        "",
        "_This file is generated by `scripts/gen_error_catalog.py`; edit that script (or `src/uncertain/diagnostics.py`) instead._",
        "",
    ]
    for kind, info in KINDS.items():
        severity = "warning" if kind.endswith("-warning") else "error"
        out += ["---", "", f"## `{kind}` ({severity})", "", info.explanation, ""]
        example = EXAMPLES.get(kind)
        if example:
            out += ["**Example:**", "```calc", example, "```", "", "**Diagnostic Output:**", "```text", render(kind, example), "```", ""]
    path = os.path.join(os.path.dirname(__file__), "..", "docs", "error-catalog.md")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.abspath(path)}")

if __name__ == "__main__":
    main()
